### PR TITLE
Update OpenJDK Docker base image to fix CVEs

### PR DESCRIPTION
**Pull request by hjacobs**
Update to latest Docker image stups openjdk                   8-26             24m ago stups_stups-go              NO_CVES_FOUND. This is just a "convenience" PR, ignore it if you want (but live with the CVEs) :smirk:

### CODE REVIEW

**Comment by ePaul** [comment]
@hjacobs Do you have a link which says which CVEs are known with the current image being used?

**Comment by hjacobs** [comment]
Sorry, wrong SSL cert, but here you go:

```
curl --insecure 'https://clair.opensource.zalan.do/v1/layers/sha256:43d4b5bcc7fc81782058d01d6468ba34003d4ef572480084dedbaba48fb8e59f?vulnerabilities&features' | jq '.Layer.Features[].Vulnerabilities|select(.!=null)'
```

**Comment by ePaul** [comment]
By now the latest version of stups/openjdk seems to be 8-29. I updated this in the branch.

**Comment by ePaul** [comment]
:+1:

**Pull request closed without merging**
